#region Game Metadata

#macro VER "1.2.0"
#macro DEV "Randoragon"
#macro ENGINE "GameMaker: Studio"
#macro COPYRIGHT "All rights reserved."

#endregion

#region Miscellaneous

#macro TRUE bool(true)
#macro FALSE bool(false)
#macro RLMCOUNT 1
#macro TOTAL_COMMON_ENEMY_COUNT (global.realm_enemy_index[RLMCOUNT] - global.realm_enemy_index[1])
#macro TWILIGHT_FURY (current_hour == 19 || current_hour == 20)
#macro SLOT_DISCLAIMER "This file was generated by Myriad Blitz " + VER + ". It is NOT meant to be viewed or edited by a human and any changes made to it are the user's own responsibility."

#endregion

#region Pixel Measurements

#macro BORDER_THICKNESS 20
#macro CANVAS_X camera_get_view_x(view_get_camera(0))
#macro CANVAS_Y camera_get_view_y(view_get_camera(0))
#macro CANVAS_WIDTH camera_get_view_width(view_get_camera(0))
#macro CANVAS_HEIGHT camera_get_view_height(view_get_camera(0))
#macro CANVAS_XEND (CANVAS_X + CANVAS_WIDTH)
#macro CANVAS_YEND (CANVAS_Y + CANVAS_HEIGHT)
#macro CANVAS_XMID lerp(CANVAS_X, CANVAS_XEND, 0.5)
#macro CANVAS_YMID lerp(CANVAS_Y, CANVAS_YEND, 0.5)
#macro GUI_X BORDER_THICKNESS
#macro GUI_Y BORDER_THICKNESS
#macro GUI_WIDTH CANVAS_WIDTH
#macro GUI_HEIGHT CANVAS_HEIGHT
#macro GUI_XEND (GUI_X + GUI_WIDTH)
#macro GUI_YEND (GUI_Y + GUI_HEIGHT)
#macro GUI_XMID lerp(GUI_X, GUI_XEND, 0.5)
#macro GUI_YMID lerp(GUI_Y, GUI_YEND, 0.5)

#endregion

#region Surfaces

#macro SURFACE_SCALE (window_get_width() / (room_width - (2 * BORDER_THICKNESS)))
#macro GENERAL_SURFACE global.general_surface
#macro GUI_SURFACE global.gui_surface

#endregion

#region Particles

#macro PART_SYSTEM_PLAYERBOT global.part_system[0]
#macro PART_SYSTEM_DAMAGE_INDICATORS global.part_system[1]
#macro PART_SYSTEM_FRAG global.part_system[2]
#macro PART_SYSTEM_CHARGE global.part_system[3]
#macro PART_SYSTEM_ENEMY global.part_system[4]
#macro PART_SYSTEM_PLAYERTOP global.part_system[5]
#macro PART_SYSTEM_ULTIMATE global.part_system[6]

#macro PART_TYPE_DISPERSE 0
#macro PART_TYPE_ULTIMATE_BURST 1
#macro PART_TYPE_INDICATORS_1 2
#macro PART_TYPE_INDICATORS_2 3
#macro PART_TYPE_INDICATORS_3 4
#macro PART_TYPE_E_ULTIMATE_LOOT 5
#macro PART_TYPE_E_GINGERBREAD_MAN_SUPER 6
#macro PART_TYPE_P_EVILFLAME_THRUSTER 7
#macro PART_TYPE_P_EVILFLAME_FURY_THRUSTER 8
#macro PART_TYPE_P_EVILFLAME_FRAG 9
#macro PART_TYPE_P_EVILFLAME_CHARGE_RING 10
#macro PART_TYPE_P_EVILFLAME_FURY_FRAG 11
#macro PART_TYPE_P_EVILFLAME_CHARGE 12
#macro PART_TYPE_P_EVILFLAME_FURY_CHARGE 13
#macro PART_TYPE_P_EVILFLAME_DUAL_CLONE_THRUSTER 14
#macro PART_TYPE_P_EMERALD_FRAG 15

#endregion

#region Status Effects

#macro STATUS_EFFECT_EXHAUSTED 0
#macro STATUS_EFFECT_MAGIC_FATIGUE 1
#macro STATUS_EFFECT_SPELL_DRIED 2
#macro STATUS_EFFECT_PARALYZED 3
#macro STATUS_EFFECT_DIZZY 4
#macro STATUS_EFFECT_DUAL_CLONE 5
#macro STATUS_EFFECT_ULTIMATE_COOLDOWN 6
#macro STATUS_EFFECT_CURRENT_CRUSH 7
#macro STATUS_EFFECT_CHIP_TUNING 8
#macro STATUS_EFFECT_TWILIGHT_FURY 9
#macro STATUS_EFFECT_BERSERK 10
#macro STATUS_EFFECT_GEAR1 11
#macro STATUS_EFFECT_GEAR2 12
#macro STATUS_EFFECT_GEAR3 13
#macro STATUS_EFFECT_GEAR4 14
#macro STATUS_EFFECT_GEAR5 15
#macro STATUS_EFFECT_GEAR6 16
#macro STATUS_EFFECT_GEAR7 17
#macro STATUS_EFFECT_GEAR8 18
#macro STATUS_EFFECT_GEAR9 19
#macro STATUS_EFFECT_GEAR10 20

#macro IS_STATUS_EFFECT_EXHAUSTED obj_player.status_effect[STATUS_EFFECT_EXHAUSTED]
#macro IS_STATUS_EFFECT_MAGIC_FATIGUE obj_player.status_effect[STATUS_EFFECT_MAGIC_FATIGUE]
#macro IS_STATUS_EFFECT_SPELL_DRIED obj_player.status_effect[STATUS_EFFECT_SPELL_DRIED]
#macro IS_STATUS_EFFECT_PARALYZED obj_player.status_effect[STATUS_EFFECT_PARALYZED]
#macro IS_STATUS_EFFECT_DIZZY obj_player.status_effect[STATUS_EFFECT_DIZZY]
#macro IS_STATUS_EFFECT_DUAL_CLONE obj_player.status_effect[STATUS_EFFECT_DUAL_CLONE]
#macro IS_STATUS_EFFECT_ULTIMATE_COOLDOWN obj_player.status_effect[STATUS_EFFECT_ULTIMATE_COOLDOWN]
#macro IS_STATUS_EFFECT_CURRENT_CRUSH obj_player.status_effect[STATUS_EFFECT_CURRENT_CRUSH]
#macro IS_STATUS_EFFECT_CHIP_TUNING obj_player.status_effect[STATUS_EFFECT_CHIP_TUNING]
#macro IS_STATUS_EFFECT_TWILIGHT_FURY obj_player.status_effect[STATUS_EFFECT_TWILIGHT_FURY]
#macro IS_STATUS_EFFECT_BERSERK obj_player.status_effect[STATUS_EFFECT_BERSERK]
#macro IS_STATUS_EFFECT_GEAR1 obj_player.status_effect[STATUS_EFFECT_GEAR1]
#macro IS_STATUS_EFFECT_GEAR2 obj_player.status_effect[STATUS_EFFECT_GEAR2]
#macro IS_STATUS_EFFECT_GEAR3 obj_player.status_effect[STATUS_EFFECT_GEAR3]
#macro IS_STATUS_EFFECT_GEAR4 obj_player.status_effect[STATUS_EFFECT_GEAR4]
#macro IS_STATUS_EFFECT_GEAR5 obj_player.status_effect[STATUS_EFFECT_GEAR5]
#macro IS_STATUS_EFFECT_GEAR6 obj_player.status_effect[STATUS_EFFECT_GEAR6]
#macro IS_STATUS_EFFECT_GEAR7 obj_player.status_effect[STATUS_EFFECT_GEAR7]
#macro IS_STATUS_EFFECT_GEAR8 obj_player.status_effect[STATUS_EFFECT_GEAR8]
#macro IS_STATUS_EFFECT_GEAR9 obj_player.status_effect[STATUS_EFFECT_GEAR9]
#macro IS_STATUS_EFFECT_GEAR10 obj_player.status_effect[STATUS_EFFECT_GEAR10]

#endregion

#region Players

#macro CHRCOUNT 4
#macro PLAYER_EVILFLAME 0
#macro PLAYER_EMERALD 1
#macro PLAYER_DER_SCOOTOMIK 2
#macro PLAYER_BOBILEUSZ 3

#endregion

#region Backwards Compatibility

#macro VER1_1_1_BG_MENU0 1
#macro VER1_1_1_BG_CHRISTMAS0 8

#endregion