#macro TRUE bool(true)
#macro FALSE bool(false)
#macro CHRCOUNT 3
#macro RLMCOUNT 1
#macro TOTAL_COMMON_ENEMY_COUNT (global.realm_enemy_index[RLMCOUNT] - global.realm_enemy_index[1])
#macro PART_SYSTEM_PLAYERBOT global.part_system[0]
#macro PART_SYSTEM_DAMAGE_INDICATORS global.part_system[1]
#macro PART_SYSTEM_FRAG global.part_system[2]
#macro PART_SYSTEM_CHARGE global.part_system[3]
#macro PART_SYSTEM_ENEMY global.part_system[4]
#macro PART_SYSTEM_PLAYERTOP global.part_system[5]
#macro PART_SYSTEM_ULTIMATE global.part_system[6]
#macro BORDER_THICKNESS 20
#macro SURFACE_SCALE (window_get_width() / (room_width - (2 * BORDER_THICKNESS)))
#macro CANVAS_X camera_get_view_x(view_get_camera(0))
#macro CANVAS_Y camera_get_view_y(view_get_camera(0))
#macro CANVAS_WIDTH camera_get_view_width(view_get_camera(0))
#macro CANVAS_HEIGHT camera_get_view_height(view_get_camera(0))
#macro CANVAS_XEND (CANVAS_X + CANVAS_WIDTH)
#macro CANVAS_YEND (CANVAS_Y + CANVAS_HEIGHT)
#macro CANVAS_XMID lerp(CANVAS_X, CANVAS_XEND, 0.5)
#macro CANVAS_YMID lerp(CANVAS_Y, CANVAS_YEND, 0.5)
#macro GUI_X BORDER_THICKNESS
#macro GUI_Y BORDER_THICKNESS
#macro GUI_WIDTH CANVAS_WIDTH
#macro GUI_HEIGHT CANVAS_HEIGHT
#macro GUI_XEND (GUI_X + GUI_WIDTH)
#macro GUI_YEND (GUI_Y + GUI_HEIGHT)
#macro GUI_XMID lerp(GUI_X, GUI_XEND, 0.5)
#macro GUI_YMID lerp(GUI_Y, GUI_YEND, 0.5)
#macro GENERAL_SURFACE global.general_surface
#macro GUI_SURFACE global.gui_surface
#macro TWILIGHT_FURY (current_hour == 19 || current_hour == 20)
#macro SLOT_DISCLAIMER "This file was generated by Myriad Blitz " + VER + ". It is NOT meant to be viewed or edited by a human and any changes made to it are the user's own responsibility."
#macro VER "1.2.0"
#macro DEV Randoragon
#macro ENGINE GameMaker: Studio
#macro COPYRIGHT All rights reserved.

// Backwards Compatibility Macros
#macro VER1_1_1_BG_MENU0 1
#macro VER1_1_1_BG_CHRISTMAS0 8