/// @description scr_PlayerGetData();

with(obj_player)
{
sprite_index=spr_evilflame+boss.chrsel;
mask_index=spr_evilflame_hitbox+boss.chrsel;
hp=global.hp;
hpmax=hp; hpmark=hp;
bdmg=global.bdmg;
bdef=global.bdef;
bpen=global.bpen;
bkb=global.bkb;
bkbres=global.bkbres;
acc=global.acc;
counteracc=global.counteracc;
spd=global.spd;
invtime=global.invtime;
foctime=global.foctime;
focus=global.foctime;
pdmg=global.pdmg;
pdef=global.pdef;
ppen=global.ppen;
pkb=global.pkb;
pkbres=global.pkbres;
pspd=global.pspd;
sacc=global.sacc;
sspd=global.sspd;
fmin=global.fmin;
fmax=global.fmax;
fdmg=global.fdmg;
fpen=global.fpen;
fkb=global.fkb;
cdmg=global.cdmg;
cpen=global.cpen;
ckb=global.ckb;
ctime=global.ctime;
ccooldown=global.ccooldown;
ucooldown=global.ucooldown;
}
